<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="teddy.lin.todobackend.service.TodoServiceTest" tests="7" skipped="0" failures="0" errors="0" timestamp="2020-08-07T04:59:58" hostname="ZHA-ITA054-W10" time="0.811">
  <properties/>
  <testcase name="should_return_updated_todo_when_update_given_id()" classname="teddy.lin.todobackend.service.TodoServiceTest" time="0.779"/>
  <testcase name="should_throw_no_such_todo_exception_when_update_given_null_id()" classname="teddy.lin.todobackend.service.TodoServiceTest" time="0.005"/>
  <testcase name="should_throw_no_such_todo_exception_when_delete_given_id()" classname="teddy.lin.todobackend.service.TodoServiceTest" time="0.003"/>
  <testcase name="should_throw_illegal_update_id_exception_when_update_given_wrong_id()" classname="teddy.lin.todobackend.service.TodoServiceTest" time="0.005"/>
  <testcase name="should_return_all_todos_when_get_all_given_none()" classname="teddy.lin.todobackend.service.TodoServiceTest" time="0.002"/>
  <testcase name="should_return_todo_when_save_given_todo()" classname="teddy.lin.todobackend.service.TodoServiceTest" time="0.001"/>
  <testcase name="should_delete_todo_when_delete_given_id()" classname="teddy.lin.todobackend.service.TodoServiceTest" time="0.01"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
